version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tasklist
    container_name: tasklist-app
    restart: unless-stopped
    working_dir: /var/www/laravel
    volumes:
      - ./:/var/www/laravel
    network_mode: host

  nginx:
    image: nginx:stable-alpine
    container_name: tasklist-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/laravel
      - ./docker-compose/nginx:/etc/nginx/conf.d
    network_mode: host
    extra_hosts:
      - "app:172.17.0.3"
